<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{0701205e-8042-4eb2-9ac5-9191561a1695}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="50" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>